### ISSUE TITLE
bsd_errno no such field in tx_api.h

### ISSUE THREAD

**Issue by ameya7295** [azure-rtos/netx#1]
struct "TX_THREAD_STRUCT" declared at tx_api.h:328 has no field "bsd_errno" nx_bsd.c:8271 
I did check in the threadx/tx_api.h ( [https://github.com/azure-rtos/threadx/blob/master/common/inc/tx_api.h] ) it is not there.

**Comment by goldscott** [comment]
@bo-ms described how to fix this in https://github.com/azure-rtos/threadx/issues/17 so I'll close this
