### ISSUE TITLE
Documentation is not clear on memory management requirements for the client

### ISSUE THREAD

**Issue by ssnover** [azure-rtos/netx#10]
I have a C++ source file that looks approximately like this:
```
bool send_msg(NX_UDP_SOCKET * socket, NX_PACKET_POOL * pool, u32 dest_ip, u16 dest_port, uint8_t * msg_buf, isize msg_len) {
    bool retVal = false;
    NX_PACKET * packet = nullptr;
    nx_packet_allocate(pool, &packet, NX_UDP_PACKET, NX_NO_WAIT);

    if (packet != nullptr) {
        if (nx_packet_data_append(packet, msg_buf, msg_len, pool, NX_NO_WAIT) == NX_SUCCESS) {
            if (nx_udp_socket_send(socket, packet, dest_ip, dest_port) == NX_SUCCESS) {
                retVal = true;
            }
        }
        nx_packet_release(packet);
    }
    return retVal;
}
```

We've run into issues that are starting to look like double-free and so I dug into `_nx_udp_socket_send` and then `_nx_ip_packet_send` and now it looks like under some error conditions, the `_nx_ip_packet_send` calls `_nx_packet_release`. However, there appear to be other cases where the application is expected to call `nx_packet_release`.

Question: under what conditions should the application call `nx_packet_release` when using this API?

I think the bug here is likely just in the documentation. If the caller's responsibility for freeing memory is conditional, it needs to be noted ([here, specifically](https://docs.microsoft.com/en-us/azure/rtos/netx/chapter4#nx_udp_socket_send)).

**Comment by goldscott** [comment]
Hi @ssnover - if any of the nx_*_send calls return successfully, they will release the packet. If they return unsuccessfully, then you have to free the packet.

**Comment by ssnover** [comment]
Not clear if the web documentation I linked is generated from a different repository where I can open an issue instead, but I think this is non-idiomatic and should be noted in the documentation for each function that handles memory like this.

**Comment by TiejunMS** [comment]
> Thanks for the clarification!
> 
> Not clear if the web documentation I linked is generated from a different repository where I can open an issue instead, but I think this is non-idiomatic and should be noted in the documentation for each function that handles memory like this.

Thanks @ssnover ! We will improve the documentation.

**Comment by TiejunMS** [comment]
Document updated.
