### ISSUE TITLE
_nx_dns_create function there no socket bind function calls

### ISSUE THREAD

**Issue by kaushaleinfo** [azure-rtos/netx#12]
Hi Team,

I am using netx6.2 library in project and we are using DHCP, DNS, HTTP as network application, I am facing issue inside _nx_dns_create function, We are creating nx_udp_socket_create but we are not binding socket, It is breaking our project functionality.
So Can I call socket bind api there ? Or is it library bug? 
Please Let me know what is your view on the same.

Thanks
Kaushal Panchal

**Comment by wenhui-xie** [comment]
Hi @kaushaleinfo, nx_udp_socket_bind function is called in APIs: nx_dns_host_by_name_get and nx_dns_host_by_address_get. When you call these APIs, the socket will be bound.

**Comment by kaushaleinfo** [comment]
Hi wenhui-xie
Understood the logic, Thanks for sharing information.
