### ISSUE TITLE
Can NetX support 802.1Q?

### ISSUE THREAD

**Issue by xzhlksh** [azure-rtos/netx#14]

**Comment by TiejunMS** [comment]
There is no support yet. If you are looking for VLAN support, this can be mostly done in network driver.

**Comment by xzhlksh** [comment]
但是在驱动层做vlan支持着实麻烦，还得考虑tail的重新计算。为什么这么多年来NetX不考虑支持802.1Q呢？

**Comment by rsmgnu** [comment]
Yes,  I also have this question ：）

**Comment by TiejunMS** [comment]
We don't plan to add VLAN support to NetX. But it will be added to NetX Duo in the future. See https://github.com/azure-rtos/netxduo/issues/79
