### ISSUE TITLE
addons/CMakeLists.txt appears to be copy-pasted from netxduo

### ISSUE THREAD

**Issue by codusnocturnus** [azure-rtos/netx#3]
- addons/CMakeLists.txt references nonexistent subdirectories (mdns, mqtt, nat, web)
- addons/CMakeLists.txt references nonexistent source files (web/nx_web_http_server.c, http/nxd_http_server.c, etc.)
- case for directory names in addons/CMakeLists.txt doesn't match filesystem names
  - please fix by making the filesystem names all lowercase

**Comment by goldscott** [comment]
Thanks for bringing this up! We're fixing this in our next release which should be coming any day now.
