### ISSUE TITLE
Error with build instructions in README

### ISSUE THREAD

**Issue by mitchmania** [azure-rtos/netx#7]
I am trying to follow the build instructions to build netx in the readme file.  When I execute

    $ cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=cmake/cortex_m4.cmake -GNinja .

I get:

    -- Using default nx_user.h file
    -- Configuring done
    CMake Error at CMakeLists.txt:17 (add_library):
      Target "netx" links to target "azrtos::threadx" but the target was not
      found.  Perhaps a find_package() call is missing for an IMPORTED target, or
      an ALIAS target is missing?

    -- Generating done
    CMake Generate step failed.  Build files cannot be regenerated correctly.

I understand these build instructions were likely copied from the threadx repo and I understand that I'd need to build threadx to build netx but I'd appreciate help or being pointed to other documentation on how to build this software. Thanks!

**Comment by ryanwinter** [comment]
Thanks @mitchmania, yes there is a problem with the instructions on how to build each of the components and we will make edits to fix this.

In terms of unblocking you now, I would refer to the [getting started guides](https://github.com/azure-rtos/getting-started) which have examples for a number of different devkits, on how to consume threadx and netxduo using their CMake system.

**Comment by ryanwinter** [comment]
Hi @mitchmania,

Let me know if you need anything else do unblock you right now. I'm going to close this issue, feel free to reopen if you are still stuck.

**Comment by mitchmania** [comment]
Thanks for pointing that out, there's some helpful examples in there.  For now I think I've got it figured out!
